# RoBERTa-Base, MSL:512

train_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "/cb/home/vinayp/bayer22/sample_dataset_bert_64/train"
    vocab_file: "/cb/home/vinayp/bayer22/sample_dataset_bert_64/vocab.txt"
    max_sequence_length: 160
    max_predictions_per_seq: 20
    shuffle: True
    shuffle_seed: 1
    do_lower: False
    batch_size: 4
    # batch_size: 4096 # for GPU(16GB) set batch_size: 8
                    # 8 * 32 = 256 with grad_accum_steps: 32
    num_workers: 4
    sort_within_batch: True
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "/cb/home/vinayp/bayer22/sample_dataset_bert_64/train"
    vocab_file: "/cb/home/vinayp/bayer22/sample_dataset_bert_64/vocab.txt"
    max_sequence_length: 160
    max_predictions_per_seq: 20
    shuffle: False
    shuffle_seed: 1 # also for deterministic masking
    do_lower: False
    batch_size: 256 # for GPU(16GB) set batch_size: 8
    num_workers: 2

model:
    disable_nsp: True  # turn off NSP head
    vocab_size: 40
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    mlm_loss_weight: 0.019 # should be 0.058 if training with max seq length 128, 0.019 with 512
    layer_norm_epsilon: 1.0e-5
    mixed_precision: True
    # enable_vts: True # Disabled for debugging due to issue with cbtorch import

optimizer:
    optimizer_type: "AdamW"
    correct_bias: True    
    weight_decay_rate: 0.01
    disable_lr_steps_reset: True
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.0001
         steps: 10000
       - scheduler: "Linear"
         initial_learning_rate: 0.0001
         end_learning_rate: 0.0
         steps: 1000000  
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0
#    grad_accum_steps: 32 # helps fit in GPU memory

runconfig:
    max_steps: 5000
    log_steps: 100
    checkpoint_steps: 5000
    seed: 1
    show_debug_metrics: False
    save_losses: True
    save_initial_checkpoint: True
    multireplica: True
       
