# GPT-2 X Large 48-layer, 1600-hidden, 16-heads, 1.5B parameters.
# https://huggingface.co/gpt2-xl/blob/main/config.json
# https://d4mucfpksywv.cloudfront.net/better-language-models/language_models_are_unsupervised_multitask_learners.pdf
train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "/cb/home/vinayp/sample_dataset_raw_h5"
    vocab_size: 50257
    max_sequence_length: 1024
    # For high utilization in weight streaming, we estimate batch size >96 seqs
    batch_size: 95
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch
    repeat: True

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "/cb/home/vinayp/sample_dataset_raw_h5"
    vocab_size: 50257
    max_sequence_length: 1024
    batch_size: 95
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

model:
    # Embedding
    vocab_size: 50257
    hidden_size: 1600
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 1024

    # Encoder
    num_hidden_layers: 48
    dropout_rate: 0.1 # https://huggingface.co/transformers/v3.0.2/model_doc/gpt2.html
    # https://huggingface.co/gpt2-xl/blob/main/config.json#L11 Since OpenAI did not share this setting
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training
    

    # Encoder - Attention
    num_heads: 16  # it was confirmed with authors that in fact it is 16 not 25
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.1 # https://huggingface.co/transformers/v3.0.2/model_doc/gpt2.html
    # following attention & ffn biases are set using https://amaarora.github.io/2020/02/18/annotatedGPT2.html
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Encoder - ffn
    filter_size: 6400 # hidden_size * 4
    nonlinearity: "gelu"
    use_ffn_bias: True
    use_bias_in_output: False # As used in https://amaarora.github.io/2020/02/18/annotatedGPT2.html

    # Cerebras parameters
    mixed_precision: True
    allow_multireplica: False

optimizer:
    optimizer_type: "AdamW"
    correct_bias: True
    weight_decay_rate: 0.011 # https://nostalgebraist.tumblr.com/post/642136680709652480/gpt2s-weight-decay/amp
    beta1: 0.9
    beta2: 0.999
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          steps: 30838 # 3083878 * 0.01(warmup) 
          end_learning_rate: 4.3e-5 # sqrt(95 / 512) * 0.0001
        - scheduler: "CosineDecay"
          initial_learning_rate: 4.3e-5 # sqrt(95 / 512) * 0.0001
          end_learning_rate: 4.3e-6 # 4.3e-5 * (1.0 - 0.9)
          decay_steps: 3053040 # 3083878 - 30838
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0

runconfig:
    max_steps: 3083878 # 300000000000 / (1024 * 512) * 512 / 95
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    show_debug_metrics: False
    save_losses: True
    eval_steps: 528 # 50257 / 95 - 1
